# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad0ffc24861af50d606b69404fd6b6a69cf0156fdcccdd92370ffabbb2cbeaf504a7bcfdc801e402a357fc333a4391259283d21d401551a9d33abf7caa5f779d

test:
  secret_key_base: 9b367e01947c4f603f41ccfc11f328e325eb2657c83c02af3feab2486e4c95ee72081e60eabca50cd32579925016bfa714e95e52e8cef11bc0c346b7aff255ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
